version: '2'
services:
  buildbot:
    build:
        context: master
    env_file:
        - common/common.env
        - common/secrets.env
        - master/db.env
    environment:
        HOSTNAME: buildbot.gdcproject.org
        BUILDBOT_DB_URL: postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}
        BUILDBOT_CONFIG_DIR: config
        BUILDBOT_WEB_URL: http://localhost:8082/
        BUILDBOT_WEB_PORT: 8082
    ports:
      - "8082:8082"

  worker-cross:
    build:
        context: workers
        args:
            TARGET: all-linux-gnu
    env_file:
        - common/common.env
        - common/secrets.env
    environment:
        HOSTNAME: worker1.dgnu.org
        WORKERNAME: gdc-ubuntu-cross
    volumes:
        - /srv/buildbot/cache:/buildbot/cache
    links:
        - buildbot
