version: '2'
services:
  ## Buildbot master service
  buildbot:
    build:
      context: master
    env_file:
      - common/common.env
      - common/secrets.env
      - master/db.env
    environment:
      BUILDBOT_DB_URL: postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}
      BUILDBOT_CONFIG_DIR: config
      BUILDBOT_WEB_PORT: 8082
    ports:
      - 127.0.0.1:8082:8082

  ## Buildbot workers
  worker-cross:
    build:
      context: workers
      args:
        TARGET: all-linux-gnu
    env_file:
      - common/common.env
      - common/secrets.env
    environment:
      WORKERNAME: gdc-ubuntu-cross
