version: '2'
services:
  buildbot:
    build:
      context: master
    env_file:
      - common/common.env
      - common/secrets.env
      - master/db.env
    environment:
      HOSTNAME: buildbot.gdcproject.org
      BUILDBOT_DB_URL: postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}
      BUILDBOT_CONFIG_DIR: config
      BUILDBOT_WEB_URL: https://buildbot.dgnu.org/
      BUILDBOT_WEB_PORT: 8082
    hostname: buildbot
    domainname: dgnu.org
    ports:
      - "127.0.0.1:8082:8082"
    links:
      - buildbot-testdb
    depends_on:
      - buildbot-testdb

  buildbot-testdb:
    env_file:
      - master/db.env
    image: "postgres:10-alpine"
    expose:
      - 5432

  worker-cross:
    build:
      context: workers
      args:
        TARGET: all-linux-gnu
    env_file:
      - common/common.env
      - common/secrets.env
    environment:
      WORKERNAME: gdc-ubuntu-cross
    hostname: worker1
    domainname: dgnu.org
    volumes:
      - /srv/buildbot/cache:/buildbot/cache
    links:
      - buildbot
